version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - $HOME/.docker/volumes/postgres/:/var/lib/postgresql/data
  memcached:
    image: memcached
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
    env_file: .env
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - $HOME/.docker/volumes/redis/:/data
