name: Ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build / push neovim to dockerhub
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: blijblijblij/neovim
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build / push neovim to ghcr.io
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: ghcr.io/${{ github.repository_owner }}/neovim
          tag: latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
